server {
    listen 80;
    server_name localhost;
    
    root /usr/share/nginx/html;

    location ~ \.(css|js|jpg|jpeg|png|gif|ico|svg|txt)$ {
        access_log off; # Hatta bu basit dosyalar için log tutma, diski yorma!
        expires max;    # Tarayıcıya "Bunu hafızaya al" de.
    }
    
    location / {
        proxy_pass http://apache_php:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
